name: Publish on Itch.IO - josephbmanley  ðŸŽ®
on: [workflow_call, workflow_dispatch]

jobs:
  release_html:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - uses: actions/download-artifact@v3
         with:
          name: build-WebGL
          path: build/WebGL
           
       - name: list-files
         run: ls -R
         working-directory: build/WebGL

       - name: using-api-josephbmanley
         uses: josephbmanley/butler-publish-itchio-action@v1.0.3
         
    env:
      BUTLER_CREDENTIALS: ${{ secrets.ITCHIO_KEY }}
      CHANNEL: HTML
      ITCH_GAME: kurzgesagt
      ITCH_USER: spark8
      PACKAGE: build/WebGL/build-WebGL
      VERSION: 1 #${{ steps.downloading.outputs.version }}


          
      
